spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Management endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
