-- Insert units data
-- Loại bỏ trùng lặp và sắp xếp theo alphabet
-- Sử dụng INSERT IGNORE để bỏ qua nếu đã tồn tại

INSERT IGNORE INTO units (unit_name) VALUES
('BĐ Hà Nội'),
('BĐ Hà Nội, BĐ Hải Phòng'),
('BĐ Hà Nội, BĐ Vĩnh Phúc'),
('BĐ Hải Phòng'),
('BĐ Khánh Hòa'),
('BĐ lô lẻ của Thương'),
('BĐ Nghệ An'),
('BĐ Ninh Bình'),
('BĐ Quảng Bình'),
('BĐ Sơn La'),
('BĐ Vĩnh Phúc'),
('BĐTT Sài Gòn - BĐ Hồ Chí Minh'),
('Bưu điện Bến Tre'),
('Bưu điện Bình Định'),
('Bưu điện Bình Phước'),
('Bưu điện Cà Mau'),
('Bưu điện Cần Thơ'),
('Bưu điện Cầu Giấy'),
('Bưu điện Chương Mỹ'),
('Bưu điện Đắk Lắk'),
('Bưu điện Đông Anh'),
('Bưu điện Đồng Nai'),
('Bưu điện Hà Đông'),
('Bưu điện Hà Tĩnh'),
('Bưu điện Hải Dương'),
('Bưu điện Hoàn Kiếm'),
('Bưu điện Huế'),
('Bưu điện Hưng Yên'),
('Bưu điện Kiên Giang'),
('Bưu điện Lạng Sơn'),
('Bưu điện Lào Cai'),
('Bưu điện Long Biên'),
('Bưu điện Nam Định'),
('Bưu điện Ninh Bình'),
('Bưu điện Phú Thọ'),
('Bưu điện Quảng Bình'),
('Bưu điện Quảng Trị'),
('Bưu điện Sơn La'),
('Bưu điện Sơn Tây'),
('Bưu điện Thái Nguyên'),
('Bưu điện Thanh Trì'),
('Bưu điện Thanh Trì - Đợt 2'),
('Bưu điện Từ Liêm'),
('Bưu điện Tuyên Quang'),
('Bưu điện Vĩnh Phúc'),
('Bưu điện Yên Bái'),
('Công ty Du lịch bưu điện'),
('Công ty Logistics'),
('Đạt - con chị Liên Hương - Công đoàn Tct Bưu điện'),
('Khách lẻ sếp Hằng'),
('Khách lẻ, BĐ An Giang, BĐ Lạng Sơn, TCT Bưu điện, BĐ Hải Phòng'),
('Kho'),
('Kho vận'),
('Lấy áo đi đo Than Thống Nhất đợt 3'),
('Logistic, BĐ HCM, BĐ Tuyên Quang'),
('Mẫu BĐ Huế - Hằng fashion'),
('Nhập lại kho đồ mượn đi đo và đồ khách trả lại'),
('Phát hành báo chí'),
('Tạm loại vì bị ố. Nếu tẩy được sẽ nhập lại'),
('Tcty Bưu điện'),
('TCT Bưu điện'),
('Thùy'),
('Toàn Huế đi đo'),
('Tổng Nét'),
('Tổng Nét, VT Hòa Bình'),
('Trường Định Công'),
('TT Đào tạo và Bồi dưỡng nghiệp vụ Bưu điện'),
('TTKD Hà Nội + BĐ Gia Lai'),
('TTKD Lai Châu, VT Thái Nguyên, TTKD Đồng Tháp, TTKD Tuyên Quang'),
('VT An Giang, BĐ Kon Tum, Cty dịch vụ số'),
('VT Hà Nội, TTKD Bắc Kạn, Cty DV Số');